# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - tools/snippet-generator

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - tools/snippet-generator

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml
    parameters:
      ToolDirectory: snippet-generator
